/**
 * Copyright (c) 2026 Tianjin University, Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * the BSD 3-Clause License (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 */

/*!
 * \file prepare_wy_repr_bwd_tiling_key.h
 * \brief Tiling key template arguments for fused prepare_wy_repr_bwd.
 */

#ifndef PREPARE_WY_REPR_BWD_TILING_KEY_H
#define PREPARE_WY_REPR_BWD_TILING_KEY_H

#include "ascendc/host_api/tiling/template_argument.h"

#define TPL_BF16 10
#define TPL_FP16 20
#define TPL_FP32 30

#define PREPARE_WY_REPR_BWD_TPL_V128 128
#define PREPARE_WY_REPR_BWD_TPL_V256 256
#define PREPARE_WY_REPR_BWD_TPL_BT64 64
#define PREPARE_WY_REPR_BWD_TPL_BT128 128

ASCENDC_TPL_ARGS_DECL(PrepareWyReprBwd,
    ASCENDC_TPL_DTYPE_DECL(D_T_K, TPL_BF16, TPL_FP16),
    ASCENDC_TPL_DTYPE_DECL(D_T_G, TPL_BF16, TPL_FP16,
                           TPL_FP32),
    ASCENDC_TPL_UINT_DECL(V_DIM, 1, ASCENDC_TPL_UI_LIST, PREPARE_WY_REPR_BWD_TPL_V128,
                          PREPARE_WY_REPR_BWD_TPL_V256),
    ASCENDC_TPL_UINT_DECL(CHUNK_SIZE, 1, ASCENDC_TPL_UI_LIST, PREPARE_WY_REPR_BWD_TPL_BT64,
                          PREPARE_WY_REPR_BWD_TPL_BT128)
);

#define PREPARE_WY_REPR_BWD_TPL_SEL_ENTRY(K_TYPE, G_TYPE, V_VALUE, BT_VALUE)                                  \
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DTYPE_SEL(D_T_K, K_TYPE),                                                \
                         ASCENDC_TPL_DTYPE_SEL(D_T_G, G_TYPE),                                                \
                         ASCENDC_TPL_UINT_SEL(V_DIM, ASCENDC_TPL_UI_LIST, V_VALUE),                           \
                         ASCENDC_TPL_UINT_SEL(CHUNK_SIZE, ASCENDC_TPL_UI_LIST, BT_VALUE))

ASCENDC_TPL_SEL(
    PREPARE_WY_REPR_BWD_TPL_SEL_ENTRY(TPL_FP16, TPL_FP16,
                                      PREPARE_WY_REPR_BWD_TPL_V128, PREPARE_WY_REPR_BWD_TPL_BT64),
    PREPARE_WY_REPR_BWD_TPL_SEL_ENTRY(TPL_FP16, TPL_FP16,
                                      PREPARE_WY_REPR_BWD_TPL_V128, PREPARE_WY_REPR_BWD_TPL_BT128),
    PREPARE_WY_REPR_BWD_TPL_SEL_ENTRY(TPL_FP16, TPL_FP16,
                                      PREPARE_WY_REPR_BWD_TPL_V256, PREPARE_WY_REPR_BWD_TPL_BT64),
    PREPARE_WY_REPR_BWD_TPL_SEL_ENTRY(TPL_FP16, TPL_FP16,
                                      PREPARE_WY_REPR_BWD_TPL_V256, PREPARE_WY_REPR_BWD_TPL_BT128),
    PREPARE_WY_REPR_BWD_TPL_SEL_ENTRY(TPL_FP16, TPL_BF16,
                                      PREPARE_WY_REPR_BWD_TPL_V128, PREPARE_WY_REPR_BWD_TPL_BT64),
    PREPARE_WY_REPR_BWD_TPL_SEL_ENTRY(TPL_FP16, TPL_BF16,
                                      PREPARE_WY_REPR_BWD_TPL_V128, PREPARE_WY_REPR_BWD_TPL_BT128),
    PREPARE_WY_REPR_BWD_TPL_SEL_ENTRY(TPL_FP16, TPL_BF16,
                                      PREPARE_WY_REPR_BWD_TPL_V256, PREPARE_WY_REPR_BWD_TPL_BT64),
    PREPARE_WY_REPR_BWD_TPL_SEL_ENTRY(TPL_FP16, TPL_BF16,
                                      PREPARE_WY_REPR_BWD_TPL_V256, PREPARE_WY_REPR_BWD_TPL_BT128),
    PREPARE_WY_REPR_BWD_TPL_SEL_ENTRY(TPL_FP16, TPL_FP32,
                                      PREPARE_WY_REPR_BWD_TPL_V128, PREPARE_WY_REPR_BWD_TPL_BT64),
    PREPARE_WY_REPR_BWD_TPL_SEL_ENTRY(TPL_FP16, TPL_FP32,
                                      PREPARE_WY_REPR_BWD_TPL_V128, PREPARE_WY_REPR_BWD_TPL_BT128),
    PREPARE_WY_REPR_BWD_TPL_SEL_ENTRY(TPL_FP16, TPL_FP32,
                                      PREPARE_WY_REPR_BWD_TPL_V256, PREPARE_WY_REPR_BWD_TPL_BT64),
    PREPARE_WY_REPR_BWD_TPL_SEL_ENTRY(TPL_FP16, TPL_FP32,
                                      PREPARE_WY_REPR_BWD_TPL_V256, PREPARE_WY_REPR_BWD_TPL_BT128),
    PREPARE_WY_REPR_BWD_TPL_SEL_ENTRY(TPL_BF16, TPL_FP16,
                                      PREPARE_WY_REPR_BWD_TPL_V128, PREPARE_WY_REPR_BWD_TPL_BT64),
    PREPARE_WY_REPR_BWD_TPL_SEL_ENTRY(TPL_BF16, TPL_FP16,
                                      PREPARE_WY_REPR_BWD_TPL_V128, PREPARE_WY_REPR_BWD_TPL_BT128),
    PREPARE_WY_REPR_BWD_TPL_SEL_ENTRY(TPL_BF16, TPL_FP16,
                                      PREPARE_WY_REPR_BWD_TPL_V256, PREPARE_WY_REPR_BWD_TPL_BT64),
    PREPARE_WY_REPR_BWD_TPL_SEL_ENTRY(TPL_BF16, TPL_FP16,
                                      PREPARE_WY_REPR_BWD_TPL_V256, PREPARE_WY_REPR_BWD_TPL_BT128),
    PREPARE_WY_REPR_BWD_TPL_SEL_ENTRY(TPL_BF16, TPL_BF16,
                                      PREPARE_WY_REPR_BWD_TPL_V128, PREPARE_WY_REPR_BWD_TPL_BT64),
    PREPARE_WY_REPR_BWD_TPL_SEL_ENTRY(TPL_BF16, TPL_BF16,
                                      PREPARE_WY_REPR_BWD_TPL_V128, PREPARE_WY_REPR_BWD_TPL_BT128),
    PREPARE_WY_REPR_BWD_TPL_SEL_ENTRY(TPL_BF16, TPL_BF16,
                                      PREPARE_WY_REPR_BWD_TPL_V256, PREPARE_WY_REPR_BWD_TPL_BT64),
    PREPARE_WY_REPR_BWD_TPL_SEL_ENTRY(TPL_BF16, TPL_BF16,
                                      PREPARE_WY_REPR_BWD_TPL_V256, PREPARE_WY_REPR_BWD_TPL_BT128),
    PREPARE_WY_REPR_BWD_TPL_SEL_ENTRY(TPL_BF16, TPL_FP32,
                                      PREPARE_WY_REPR_BWD_TPL_V128, PREPARE_WY_REPR_BWD_TPL_BT64),
    PREPARE_WY_REPR_BWD_TPL_SEL_ENTRY(TPL_BF16, TPL_FP32,
                                      PREPARE_WY_REPR_BWD_TPL_V128, PREPARE_WY_REPR_BWD_TPL_BT128),
    PREPARE_WY_REPR_BWD_TPL_SEL_ENTRY(TPL_BF16, TPL_FP32,
                                      PREPARE_WY_REPR_BWD_TPL_V256, PREPARE_WY_REPR_BWD_TPL_BT64),
    PREPARE_WY_REPR_BWD_TPL_SEL_ENTRY(TPL_BF16, TPL_FP32,
                                      PREPARE_WY_REPR_BWD_TPL_V256, PREPARE_WY_REPR_BWD_TPL_BT128)
);

#undef PREPARE_WY_REPR_BWD_TPL_SEL_ENTRY

#endif // PREPARE_WY_REPR_BWD_TILING_KEY_H
