/**
 * Copyright (c) 2026 Tianjin University, Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * the BSD 3-Clause License (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 */

/*!
 * \file chunk_bwd_dqkwg_struct.h
 * \brief Tiling data struct and tiling key declarations for chunk_bwd_dqkwg operator.
 */

#ifndef CHUNK_BWD_DQKWG_STRUCT_H
#define CHUNK_BWD_DQKWG_STRUCT_H

#ifndef TORCH_MODE
#include "ascendc/host_api/tiling/template_argument.h"
#endif

namespace GDN {

#define CHUNK_BWD_DQKWG_STRATEGY_FIX_LEN 0
#define CHUNK_BWD_DQKWG_STRATEGY_VAR_LEN 1

#define CHUNK_BWD_DQKWG_TPL_BF16 10
#define CHUNK_BWD_DQKWG_TPL_FP16 20
#define CHUNK_BWD_DQKWG_TPL_FP32 30

#ifndef TORCH_MODE
ASCENDC_TPL_ARGS_DECL(ChunkBwdDqkwg,
    ASCENDC_TPL_UINT_DECL(strategy, 1, ASCENDC_TPL_UI_LIST, CHUNK_BWD_DQKWG_STRATEGY_FIX_LEN, CHUNK_BWD_DQKWG_STRATEGY_VAR_LEN),
    ASCENDC_TPL_DTYPE_DECL(D_T_Q, CHUNK_BWD_DQKWG_TPL_BF16, CHUNK_BWD_DQKWG_TPL_FP16),
    ASCENDC_TPL_DTYPE_DECL(D_T_G, CHUNK_BWD_DQKWG_TPL_BF16, CHUNK_BWD_DQKWG_TPL_FP16, CHUNK_BWD_DQKWG_TPL_FP32),
    ASCENDC_TPL_UINT_DECL(V, 1, ASCENDC_TPL_UI_LIST, 128, 256),
);

ASCENDC_TPL_SEL(
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_UINT_SEL(strategy, ASCENDC_TPL_UI_LIST, CHUNK_BWD_DQKWG_STRATEGY_FIX_LEN),
        ASCENDC_TPL_DTYPE_SEL(D_T_Q, CHUNK_BWD_DQKWG_TPL_BF16),
        ASCENDC_TPL_DTYPE_SEL(D_T_G, CHUNK_BWD_DQKWG_TPL_BF16),
        ASCENDC_TPL_UINT_SEL(V, ASCENDC_TPL_UI_LIST, 128),
    ),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_UINT_SEL(strategy, ASCENDC_TPL_UI_LIST, CHUNK_BWD_DQKWG_STRATEGY_FIX_LEN),
        ASCENDC_TPL_DTYPE_SEL(D_T_Q, CHUNK_BWD_DQKWG_TPL_BF16),
        ASCENDC_TPL_DTYPE_SEL(D_T_G, CHUNK_BWD_DQKWG_TPL_BF16),
        ASCENDC_TPL_UINT_SEL(V, ASCENDC_TPL_UI_LIST, 256),
    ),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_UINT_SEL(strategy, ASCENDC_TPL_UI_LIST, CHUNK_BWD_DQKWG_STRATEGY_FIX_LEN),
        ASCENDC_TPL_DTYPE_SEL(D_T_Q, CHUNK_BWD_DQKWG_TPL_FP16),
        ASCENDC_TPL_DTYPE_SEL(D_T_G, CHUNK_BWD_DQKWG_TPL_FP16),
        ASCENDC_TPL_UINT_SEL(V, ASCENDC_TPL_UI_LIST, 128),
    ),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_UINT_SEL(strategy, ASCENDC_TPL_UI_LIST, CHUNK_BWD_DQKWG_STRATEGY_FIX_LEN),
        ASCENDC_TPL_DTYPE_SEL(D_T_Q, CHUNK_BWD_DQKWG_TPL_FP16),
        ASCENDC_TPL_DTYPE_SEL(D_T_G, CHUNK_BWD_DQKWG_TPL_FP16),
        ASCENDC_TPL_UINT_SEL(V, ASCENDC_TPL_UI_LIST, 256),
    ),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_UINT_SEL(strategy, ASCENDC_TPL_UI_LIST, CHUNK_BWD_DQKWG_STRATEGY_FIX_LEN),
        ASCENDC_TPL_DTYPE_SEL(D_T_Q, CHUNK_BWD_DQKWG_TPL_BF16),
        ASCENDC_TPL_DTYPE_SEL(D_T_G, CHUNK_BWD_DQKWG_TPL_FP32),
        ASCENDC_TPL_UINT_SEL(V, ASCENDC_TPL_UI_LIST, 128),
    ),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_UINT_SEL(strategy, ASCENDC_TPL_UI_LIST, CHUNK_BWD_DQKWG_STRATEGY_FIX_LEN),
        ASCENDC_TPL_DTYPE_SEL(D_T_Q, CHUNK_BWD_DQKWG_TPL_BF16),
        ASCENDC_TPL_DTYPE_SEL(D_T_G, CHUNK_BWD_DQKWG_TPL_FP32),
        ASCENDC_TPL_UINT_SEL(V, ASCENDC_TPL_UI_LIST, 256),
    ),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_UINT_SEL(strategy, ASCENDC_TPL_UI_LIST, CHUNK_BWD_DQKWG_STRATEGY_FIX_LEN),
        ASCENDC_TPL_DTYPE_SEL(D_T_Q, CHUNK_BWD_DQKWG_TPL_FP16),
        ASCENDC_TPL_DTYPE_SEL(D_T_G, CHUNK_BWD_DQKWG_TPL_FP32),
        ASCENDC_TPL_UINT_SEL(V, ASCENDC_TPL_UI_LIST, 128),
    ),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_UINT_SEL(strategy, ASCENDC_TPL_UI_LIST, CHUNK_BWD_DQKWG_STRATEGY_FIX_LEN),
        ASCENDC_TPL_DTYPE_SEL(D_T_Q, CHUNK_BWD_DQKWG_TPL_FP16),
        ASCENDC_TPL_DTYPE_SEL(D_T_G, CHUNK_BWD_DQKWG_TPL_FP32),
        ASCENDC_TPL_UINT_SEL(V, ASCENDC_TPL_UI_LIST, 256),
    ),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_UINT_SEL(strategy, ASCENDC_TPL_UI_LIST, CHUNK_BWD_DQKWG_STRATEGY_VAR_LEN),
        ASCENDC_TPL_DTYPE_SEL(D_T_Q, CHUNK_BWD_DQKWG_TPL_BF16),
        ASCENDC_TPL_DTYPE_SEL(D_T_G, CHUNK_BWD_DQKWG_TPL_BF16),
        ASCENDC_TPL_UINT_SEL(V, ASCENDC_TPL_UI_LIST, 128),
    ),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_UINT_SEL(strategy, ASCENDC_TPL_UI_LIST, CHUNK_BWD_DQKWG_STRATEGY_VAR_LEN),
        ASCENDC_TPL_DTYPE_SEL(D_T_Q, CHUNK_BWD_DQKWG_TPL_BF16),
        ASCENDC_TPL_DTYPE_SEL(D_T_G, CHUNK_BWD_DQKWG_TPL_BF16),
        ASCENDC_TPL_UINT_SEL(V, ASCENDC_TPL_UI_LIST, 256),
    ),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_UINT_SEL(strategy, ASCENDC_TPL_UI_LIST, CHUNK_BWD_DQKWG_STRATEGY_VAR_LEN),
        ASCENDC_TPL_DTYPE_SEL(D_T_Q, CHUNK_BWD_DQKWG_TPL_FP16),
        ASCENDC_TPL_DTYPE_SEL(D_T_G, CHUNK_BWD_DQKWG_TPL_FP16),
        ASCENDC_TPL_UINT_SEL(V, ASCENDC_TPL_UI_LIST, 128),
    ),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_UINT_SEL(strategy, ASCENDC_TPL_UI_LIST, CHUNK_BWD_DQKWG_STRATEGY_VAR_LEN),
        ASCENDC_TPL_DTYPE_SEL(D_T_Q, CHUNK_BWD_DQKWG_TPL_FP16),
        ASCENDC_TPL_DTYPE_SEL(D_T_G, CHUNK_BWD_DQKWG_TPL_FP16),
        ASCENDC_TPL_UINT_SEL(V, ASCENDC_TPL_UI_LIST, 256),
    ),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_UINT_SEL(strategy, ASCENDC_TPL_UI_LIST, CHUNK_BWD_DQKWG_STRATEGY_VAR_LEN),
        ASCENDC_TPL_DTYPE_SEL(D_T_Q, CHUNK_BWD_DQKWG_TPL_BF16),
        ASCENDC_TPL_DTYPE_SEL(D_T_G, CHUNK_BWD_DQKWG_TPL_FP32),
        ASCENDC_TPL_UINT_SEL(V, ASCENDC_TPL_UI_LIST, 128),
    ),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_UINT_SEL(strategy, ASCENDC_TPL_UI_LIST, CHUNK_BWD_DQKWG_STRATEGY_VAR_LEN),
        ASCENDC_TPL_DTYPE_SEL(D_T_Q, CHUNK_BWD_DQKWG_TPL_BF16),
        ASCENDC_TPL_DTYPE_SEL(D_T_G, CHUNK_BWD_DQKWG_TPL_FP32),
        ASCENDC_TPL_UINT_SEL(V, ASCENDC_TPL_UI_LIST, 256),
    ),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_UINT_SEL(strategy, ASCENDC_TPL_UI_LIST, CHUNK_BWD_DQKWG_STRATEGY_VAR_LEN),
        ASCENDC_TPL_DTYPE_SEL(D_T_Q, CHUNK_BWD_DQKWG_TPL_FP16),
        ASCENDC_TPL_DTYPE_SEL(D_T_G, CHUNK_BWD_DQKWG_TPL_FP32),
        ASCENDC_TPL_UINT_SEL(V, ASCENDC_TPL_UI_LIST, 128),
    ),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_UINT_SEL(strategy, ASCENDC_TPL_UI_LIST, CHUNK_BWD_DQKWG_STRATEGY_VAR_LEN),
        ASCENDC_TPL_DTYPE_SEL(D_T_Q, CHUNK_BWD_DQKWG_TPL_FP16),
        ASCENDC_TPL_DTYPE_SEL(D_T_G, CHUNK_BWD_DQKWG_TPL_FP32),
        ASCENDC_TPL_UINT_SEL(V, ASCENDC_TPL_UI_LIST, 256),
    ),
);
#endif

struct ChunkBwdDqkwgTilingData {
    int64_t B;
    int64_t HV;
    int64_t HK;
    int64_t T;
    int64_t K;
    int64_t V;
    int64_t BT;
    int64_t numChunks;
    float scale;
    int64_t mul0RowNum;
    int64_t wsDwOffset;
    int64_t wsDgLastOffset;
    int64_t dgLastSize;
    int64_t wsMm5Offset;
    int64_t wsDsTempOffset;
    int64_t totalWorkspaceSize;
    int64_t isVarLen;
};

} // namespace GDN

#endif // CHUNK_BWD_DQKWG_STRUCT_H
