#ifndef CHUNK_SCALED_DOT_KKT_TILING_KEY_H
#define CHUNK_SCALED_DOT_KKT_TILING_KEY_H

#include "tiling/template_argument.h"

#define CHUNK_SCALED_DOT_KKT_BT64 0
#define CHUNK_SCALED_DOT_KKT_BT16 1
#define CHUNK_SCALED_DOT_KKT_BT32 2
#define CHUNK_SCALED_DOT_KKT_BT128 3
#define CHUNK_SCALED_DOT_KKT_TPL_FP16 10
#define CHUNK_SCALED_DOT_KKT_TPL_BF16 20

ASCENDC_TPL_ARGS_DECL(ChunkScaledDotKkt,
    ASCENDC_TPL_DTYPE_DECL(D_T_K, CHUNK_SCALED_DOT_KKT_TPL_FP16, CHUNK_SCALED_DOT_KKT_TPL_BF16),
    ASCENDC_TPL_UINT_DECL(CHUNK_KEY, ASCENDC_TPL_2_BW, ASCENDC_TPL_UI_LIST,
                          CHUNK_SCALED_DOT_KKT_BT64, CHUNK_SCALED_DOT_KKT_BT16,
                          CHUNK_SCALED_DOT_KKT_BT32, CHUNK_SCALED_DOT_KKT_BT128)
);

ASCENDC_TPL_SEL(
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_DTYPE_SEL(D_T_K, CHUNK_SCALED_DOT_KKT_TPL_FP16),
        ASCENDC_TPL_UINT_SEL(CHUNK_KEY, ASCENDC_TPL_UI_LIST, CHUNK_SCALED_DOT_KKT_BT64)
    ),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_DTYPE_SEL(D_T_K, CHUNK_SCALED_DOT_KKT_TPL_FP16),
        ASCENDC_TPL_UINT_SEL(CHUNK_KEY, ASCENDC_TPL_UI_LIST, CHUNK_SCALED_DOT_KKT_BT16)
    ),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_DTYPE_SEL(D_T_K, CHUNK_SCALED_DOT_KKT_TPL_FP16),
        ASCENDC_TPL_UINT_SEL(CHUNK_KEY, ASCENDC_TPL_UI_LIST, CHUNK_SCALED_DOT_KKT_BT32)
    ),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_DTYPE_SEL(D_T_K, CHUNK_SCALED_DOT_KKT_TPL_FP16),
        ASCENDC_TPL_UINT_SEL(CHUNK_KEY, ASCENDC_TPL_UI_LIST, CHUNK_SCALED_DOT_KKT_BT128)
    ),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_DTYPE_SEL(D_T_K, CHUNK_SCALED_DOT_KKT_TPL_BF16),
        ASCENDC_TPL_UINT_SEL(CHUNK_KEY, ASCENDC_TPL_UI_LIST, CHUNK_SCALED_DOT_KKT_BT64)
    ),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_DTYPE_SEL(D_T_K, CHUNK_SCALED_DOT_KKT_TPL_BF16),
        ASCENDC_TPL_UINT_SEL(CHUNK_KEY, ASCENDC_TPL_UI_LIST, CHUNK_SCALED_DOT_KKT_BT16)
    ),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_DTYPE_SEL(D_T_K, CHUNK_SCALED_DOT_KKT_TPL_BF16),
        ASCENDC_TPL_UINT_SEL(CHUNK_KEY, ASCENDC_TPL_UI_LIST, CHUNK_SCALED_DOT_KKT_BT32)
    ),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_DTYPE_SEL(D_T_K, CHUNK_SCALED_DOT_KKT_TPL_BF16),
        ASCENDC_TPL_UINT_SEL(CHUNK_KEY, ASCENDC_TPL_UI_LIST, CHUNK_SCALED_DOT_KKT_BT128)
    )
);

#endif  // CHUNK_SCALED_DOT_KKT_TILING_KEY_H
